### ISSUE TITLE
Improve server profile template idempotency 

### ISSUE THREAD

**Issue by abiliogp** [HewlettPackard/oneview-puppet#101]
### Scenario/Intent
On some usage scenarios, when running with the 'present' ensurable, the server profile template does not behave idempotently as expected and makes calls when it shouldn't. 

### Environment Details
*Puppet module for HPE OneView Version:* 2.0.0
*OneView SDK Version:* 3.1.0
*OneView Appliance Version:* 3.0
*OneView Client API Version:* 300
*Puppet Version:* 4.8
*Ruby Version:* 2.2.6
*Platform:* Windows

### Steps to Reproduce
Run complete scenarios with server profile template, specifying as many options as possible.

### Expected Result
If there are no changes between manifest runs, or if the change is something which should not matter, like order on a hash, then no create/update/patch calls should be made to OneView since it should be able to notice nothing has changed.

### Actual Result
On some scenarios it actually does not act as expected and runs update calls.

**Comment by marikrg** [comment]
Reopening the issue. SPT Idempotency doesn't work with complex data.
