### ISSUE TITLE
Create or update uplink sets through logical interconnect groups

### ISSUE THREAD

**Issue by fgbulsoni** [HewlettPackard/oneview-puppet#105]
### Scenario/Intent
Mimic the GUI in creating the uplink sets through the LIG

### Environment Details
 - **Puppet module for HPE OneView Version:** 2.2.0

### Steps to Reproduce
Try to create it, currently puppet module only supports adding the uplink sets

### Expected Result
should be able to pass in all the configs for the uplink set and create it/update it through the lig

### Actual Result
Currently not supported

**Comment by frippe75** [comment]
Thanks for opening up the issue for me.

Adding my trace of the LIG creation that works via the Oneview gui.
[REST-call-LIG-with-uplinks-post.txt](https://github.com/HewlettPackard/oneview-puppet/files/781465/REST-call-LIG-with-uplinks-post.txt)

I think there is also a miss in the Oneview rest-api specification. Will file an issue there as well and link it back
