### ISSUE TITLE
"Artifact Bundle with Server Profile" manifest - Step by step

### ISSUE THREAD

**Issue by marikrg** [HewlettPackard/oneview-puppet#137]
### Scenario/Intent

It aims to demonstrate how to create a Deployment Plan with a minimal bootable OS Image, using all the Image Streamer Puppet resources. 

This manifest must be based on the example previously created (issue #126/ PR https://github.com/HewlettPackard/oneview-puppet/pull/131).

The main difference is that this manifest must create all the artifacts - Deployment Plan, Plan Scripts, Build Plans, and Golden Image - using the Puppet modules, instead of just upload a zip file containing all artifacts previously created.

### Environment Details
-**Puppet module for HPE OneView Version:** 2.2.0
-**OneView SDK Version:** 3.1.0
-**OneView Appliance Version:** 3.0
-**OneView Client API Version:** 300
-**Puppet Version:** 4.8
-**Ruby Version:** 2.2.6
-**Platform:** Windows/Linux

### Steps to Reproduce
Try to run the manifest "Artifact Bundle with Server Profile - Step by step"

### Expected Result
Make the example manifest available.
All artifacts must be created through the Puppet modules instead of a uploaded zip file.

### Actual Result
There is no example of how to create a server profile with a deployment plan.

**Comment by VenkateshRavula** [comment]
We will add manifest for SP creation with OSDP in sp example file.

https://github.com/HewlettPackard/oneview-puppet/pull/131/files#diff-4e3ec0a980f926ca157809df24f8f9fe

**Comment by VenkateshRavula** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
