### ISSUE TITLE
Oneview_storage_pool should not destroy and recreate a storage pool if it differs from expected

### ISSUE THREAD

**Issue by fgbulsoni** [HewlettPackard/oneview-puppet#144]
### Scenario/Intent
Currently, the `ensure: present` for the oneview_storage_pool will try to drop and recreate a storage pool if it differs from the expected.
The storage pool might be in use or dropping it could cause issues. Instead of dropping it, a message should be displayed to the user that the resource differs from expected, and allow the user to decide on how to proceed.

Optional: implement a 'force' operation to run the drop/recreate following the user's will.

**Comment by VenkateshRavula** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
