### ISSUE TITLE
SAS Logical Interconnect Group - Name to URI conversion fails on logicalInterconnectGroupUri fields

### ISSUE THREAD

**Issue by fgbulsoni** [HewlettPackard/oneview-puppet#151]
### Scenario/Intent
Pass in a name of a SAS LIG instead of a URI in a puppet manifest.

### Environment Details
 - **Puppet module for HPE OneView Version:** 2.2.0

### Steps to Reproduce
Run a manifest where a SAS LIG `name` is given in a `LogicalInterconnectGroupURI` field.

i.e.:
```ruby
oneview_enclosure_group{'Enclosure Group Create':
    ensure => 'present',
    data   => {
      name                        => 'TEST_with_sas',
      stackingMode                => 'Enclosure',
      # interconnectBayMappingCount => '8',
      interconnectBayMappings     =>
      [
        {
           interconnectBay             => '1',
           logicalInterconnectGroupUri => 'SASTEST'
         },
         {
           interconnectBay             => '4',
           logicalInterconnectGroupUri => 'SASTEST'
         },
      ],
    }
}
```

### Expected Result
Should automatically swap the name for the URI to make the calls.

### Actual Result
Returns a `resource not found` error, since it is looking strictly for `Logical Interconnect Group` resources and not `SAS Logical Interconnect Group`

**Comment by frippe75** [comment]
Was just about to open this up but it looks exactly like yersterdays issue. Thanks!

**Comment by fgbulsoni** [comment]
> Was just about to open this up but it looks exactly like yersterdays issue. Thanks!

@frippe75 Fix is in, please be sure to update your repository and let us know if you hit something else.
Cheers :octocat:
