### ISSUE TITLE
Not able to pass array to create a resource

### ISSUE THREAD

**Issue by sijeesh** [HewlettPackard/oneview-puppet#194]
### Scenario/Intent
Trying to pass an array of enclosure URIs for creating logical enclosure, but its not working.
Error::
  File :https://github.com/HewlettPackard/oneview-puppet/blob/master/lib/puppet/provider/uri_parsing.rb
  Method: uri_recursive_hash
  
### Environment Details
   Library issue

### Steps to Reproduce
 pass array of enclosure URIs for creating a logical enclosure

### Expected Result
 Resource has to be created on oneview

### Actual Result
Raise an exception with message "Need unique fields to fetch the resource"

**Comment by VenkateshRavula** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
