### ISSUE TITLE
New to Puppet

### ISSUE THREAD

**Issue by ckurka** [HewlettPackard/oneview-puppet#206]
### Scenario/Intent
Trying to run a simple manifest and I am receiving this

Notice: Compiled catalog for puppet.atlpss.hp.net in environment production in 0.05 seconds
Error: Could not find a suitable provider for oneview_server_hardware
Error: Could not find a suitable provider for oneview_server_profile
Notice: Applied catalog in 0.07 seconds

I may be just missing something simple in my setup

### Environment Details
 - **Puppet module for HPE OneView Version:** v2.2.2
 - **OneView SDK Version:** oneview-sdk (5.5.0)
 - **OneView Appliance Version:** 4.00.09
 - **OneView Client API Version:**600
 - **Puppet Version:** 5.5.2
 - **Ruby Version:** ruby-2.4.1
 - **Platform:** CentOS Linux release 7.3.1611 (Core)

### Steps to Reproduce
 puppet apply serverprofile.pp

### Expected Result
New Server Profile Applied

### Actual Result
Debug: Failed to load library 'oneview-sdk' for feature 'oneview': cannot load such file -- addressable
Debug: Puppet::Type::Oneview_server_hardware::ProviderC7000: feature oneview is missing
Debug: Failed to load library 'oneview-sdk' for feature 'oneview': cannot load such file -- addressable
Debug: Puppet::Type::Oneview_server_hardware::ProviderSynergy: feature oneview is missing
Debug: Class[Main]: Resource is being skipped, unscheduling all events
Debug: Stage[main]: Resource is being skipped, unscheduling all events
Error: Could not find a suitable provider for oneview_server_hardware
Error: Could not find a suitable provider for oneview_server_profile

Here is my manifest

# Vars
$server_profile_name = 'Server profile with OS Deployment Plan - PUPPET DEMO'
$server_hardware_name = '2-SYNERGY105-M, bay 2'
$server_hardware_type = 'SY 480 Gen9 1'
$network_1 = 'Mgmt'
$network_2 = 'Deploy'
$deployment_plan_name = 'RHEL74_SUT'
# Powering off the server in order to apply the Server Profile
# WARNING: This is a non-idempotent operation
oneview_server_hardware{'Server Hardware Power Off':
    ensure => 'set_power_state',
    data   => {
      hostname    => $server_hardware_name,
      power_state => 'off',
    },
}

# Create and apply a Server Profile, using Image Streamer to deploy the OS
oneview_server_profile{'Server Profile Creation':
  ensure => 'present',
  data   =>
  {
    name                  => $server_profile_name,
    serverHardwareUri     => $server_hardware_name,
    serverHardwareTypeUri => $server_hardware_type,
    osDeploymentSettings  => {
      osDeploymentPlanUri => $deployment_plan_name
    },
    boot                  => {
      manageBoot => true,
      order      => [ 'HardDisk' ]
    },
    bootMode              => {
      manageMode    => true,
      pxeBootPolicy => 'Auto',
      mode          => 'UEFIOptimized',
    },
    connections           => [
      {
        id            => 1,
        name          => 'connection1',
        functionType  => 'Ethernet',
        networkUri    => $network_1,
        requestedMbps => 2500,
        requestedVFs  => 'Auto',
        boot          => {
          priority            => 'NotBootable',
        }
      },
      {
        id            => 2,
        name          => 'connection2',
        functionType  => 'Ethernet',
        networkUri    => $network_2,
        requestedMbps => 2500,
        requestedVFs  => 'Auto',
        boot          => {
          priority            => 'Primary',
          initiatorNameSource => 'ProfileInitiatorName'
        }
      },
      {
        id            => 3,
        name          => 'connection3',
        functionType  => 'Ethernet',
        networkUri    => $network_2,
        requestedMbps => 2500,
        requestedVFs  => 'Auto',
        boot          => {
          priority            => 'Secondary',
          initiatorNameSource => 'ProfileInitiatorName'
        }
      }
    ]
  }
}

# Power on the Server Hardware after the Server Profile has been applied
# WARNING: This is a non-idempotent operation
oneview_server_hardware{'Server Hardware Power On':
    ensure => 'set_power_state',
    data   => {
      hostname    => $server_hardware_name,
      power_state => 'on',
    },
}

**Comment by madhav-bharadwaj** [comment]
Hi ckurka, This seems to be an issue with your setup. Let us know if the below checklist is complete:

1. Have you installed oneview puppet module yet? `puppet module install hewlettpackard-oneview`
2. Is your directory name "oneview" and not "oneview-puppet".
3. Are you running your manifest from the examples directory?
4. If yes to all the above, can you try `puppet apply serverprofile.pp --modulepath <Path to your oneview puppet module>`

If still it doesn't work, please share the steps you have performed in your setup.

**Comment by ckurka** [comment]
Madhav,

Thanks... I tried that and I am still seeing the same thing. Let me try a clean install. the steps I followed was.
1. Install OS (Centos 7.3) and required RPMs
2. Install RVM
3. Install Ruby
4. Install the OV Ruby SDK
5. Installed Puppet

-Chris

**Comment by madhav-bharadwaj** [comment]
Note: Oneview puppet module for api600 is not yet released. The support for most of the resources are already available in the git repo. So include `--modulepath` option to make use of them.
