### ISSUE TITLE
Create a ServerProfileTemplate with a firmwareBaselineUri by resource Name for API 800/1000/1200

### ISSUE THREAD

**Issue by riconem** [HewlettPackard/oneview-puppet#215]
### Scenario/Intent
Create a ServerProfileTemplate with a firmwareBaselineUri by resource Name

### Environment Details
 - **Puppet module for HPE OneView Version:** 2.3.0
 - **OneView SDK Version:** [5.7.0]
 - **OneView Appliance Version:** 5.00.00.02-0404934
 - **OneView Client API Version:** 800
 - **Puppet Version:** 5.5.16
 - **Ruby Version:** 2.4.5
 - **Platform:** Oracle Linux Server 7.7

### Steps to Reproduce
Create a ServerProfileTemplate with a firmwareBaselineUri. Here you have to set the name of the resource as firmwareBaselineUri not the actual URI.

### Expected Result
Creating of a new ServerProfileTemplate

### Actual Result
**Error:**
`Error:/Stage[main]/Oneviewconf/Oneview_server_profile_template[SMOPS_RefDCN_HAN2_HotNode]: Could not evaluate: uninitialized constant OneviewSDK::API800::Synergy::FirmwareDriver`

### Guess
The problem is that FirmwareDriver is only supported up to API 300 in the [sdk](https://github.com/HewlettPackard/oneview-sdk-ruby/blob/master/endpoints-support.md).
In this example we use the uri_parsing.rb because of "resource name as URI" which executes [get_class()](https://github.com/HewlettPackard/oneview-puppet/blob/5e81fa97499071b8fbe873106f3d92dc6b4aecbe/lib/puppet/provider/uri_parsing.rb#L113). Here it crashes because it trys to search the FirmwareDriver on API 800.

**Comment by jyothisgm** [comment]
Firmware resources are not supported for version 800. 
Please try it with version 500 which is supported for firmware resources. We have tested it for the version.
Please see https://github.com/HewlettPackard/oneview-sdk-ruby/blob/master/endpoints-support.md.
Let us know if any more issues arise.

**Comment by VenkateshRavula** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
