### ISSUE TITLE
Not able to pass connection names in the SPT creation as the networkUri is not parsing in the connectionSettings

### ISSUE THREAD

**Issue by soodpr** [HewlettPackard/oneview-puppet#218]
### Scenario/Intent
Not able to pass connection names in the SPT creation as the networkUri is not parsing in the connectionSettings

### Environment Details
 - **Puppet module for HPE OneView Version:** NA
 - **OneView SDK Version:** 5.8.0
 - **OneView Appliance Version:** 5.0
 - **OneView Client API Version:**1200
 - **Puppet Version:** 5.5
 - **Ruby Version:** 2.41
 - **Platform:** Ubuntu

### Steps to Reproduce
Create SPT with connection settings with conenction names instead of network URI

### Expected Result
SPT created successfully

### Actual Result
It failed with an OneView error :
Error: /Stage[main]/Main/Oneview_server_profile_template[Server Profile Template Create]/ensure: change from 'absent' to 'present' failed: Could not set 'present' on ensure: Task ended with bad state: 'Error'.
Response: [
  {
    "errorCode": "PortIdRequiredForConnection",
    "message": "Port must be specified for connection 1 with network {\"name\":\"Unknown\", \"uri\":\"FC01\"}.",
    "details": "",
    "recommendedActions": [
      "Assign connection 1 to one of the available ports."
    ],
    "errorSource": null,
    "nestedErrors": [

    ],
    "data": {
    }
  }
]

**Comment by VenkateshRavula** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
