### ISSUE TITLE
add helper method to parse SAN storage volumeURI in SPT creation

### ISSUE THREAD

**Issue by soodpr** [HewlettPackard/oneview-puppet#220]
### Scenario/Intent
add helper method to parse SAN storage volumeURI in SPT creation

### Steps to Reproduce
Currently, we have to pass volumeUri in the SPT creation for adding SAN storage 

### Expected Result
Parse either volume name or uri

### Actual Result
Able to create SPT with SAN storage by passing volume uri only

**Comment by VenkateshRavula** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
