### ISSUE TITLE
Fully document all methods

### ISSUE THREAD

**Issue by fgbulsoni** [HewlettPackard/oneview-puppet#44]
### Scenario/Intent
Inch CI is showing some undocumented methods. Should look into those and make sure everything is either documented or look into disabling Inch CI for what is not relevant/should not be documented.

### Environment Details
 - **Puppet module for HPE OneView Version:** 2.0.0

### Steps to Reproduce
Check the Inch CI in the readme or https://inch-ci.org/github/HewlettPackard/oneview-puppet

### Expected Result
See no undocumented methods

### Actual Result
There's something like 1/3 methods that are undocumented. Those should be documented or if the CI is expecting documentation where it would not make sense, a way to clearly show that would also be good.

**Comment by VenkateshRavula** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
