### ISSUE TITLE
Unit tests on unexpected scenarios

### ISSUE THREAD

**Issue by fgbulsoni** [HewlettPackard/oneview-puppet#55]
### Scenario/Intent
Run unit tests on a file with API 200 and Synergy hardware variant.

### Steps to Reproduce
Run unit tests on a file with API 200 and Synergy hardware variant.

### Expected Result
I get only the c7000 unit tests for 200, as synergy was not supported in 200.

### Actual Result
It tries to run Synergy with 200 and fails due to uninitialized constant.

**Comment by marikrg** [comment]
@fgbulsoni 
Is it still valid, since the issue #103 was solved?
I believe this error will not happen anymore.

**Comment by fgbulsoni** [comment]
As long as this has been tested and passing I see no problem with the issue being closed.
