### ISSUE TITLE
Implement GET endpoint as FACTS

### ISSUE THREAD

**Issue by fgbulsoni** [HewlettPackard/oneview-puppet#63]
### Scenario/Intent
Use the information from a get endpoint as an input or variable for a resource declaration

### Environment Details
 - **Puppet module for HPE OneView Version:** 2.0.0
 - **OneView SDK Version:** 3.1.0
 - **OneView Appliance Version:** 3.0
 - **OneView Client API Version:** 300
 - **Puppet Version:** 4.8
 - **Ruby Version:** 2.2.6
 - **Platform:** Windows

### Steps to Reproduce
Feature not implemented - no steps to reproduce

### Expected Result
Expected meaningful facts with output that can be used as variables on resource declarations

### Actual Result
Currently no facts are available for this module

**Comment by fgbulsoni** [comment]
A different idea might also be to implement a custom Puppet function for a generic find_by using the oneview-sdk and receiving the resource type to be searched.
This would also allow for calling the function inside the manifests and may be as reliable as, or even more reliable than a FACT.

**Comment by VenkateshRavula** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
