### ISSUE TITLE
Transfer idempotency verifications to the SDK

### ISSUE THREAD

**Issue by fgbulsoni** [HewlettPackard/oneview-puppet#66]
### Scenario/Intent
Use the SDK ``like`` method instead of custom `find_bys` for ensuring idempotency on resources 

### Environment Details
*Puppet module for HPE OneView Version:* 2.0.0
*OneView SDK Version:* 3.1.0
*OneView Appliance Version:* 3.0
*OneView Client API Version:* 300
*Puppet Version:* 4.8
*Ruby Version:* 2.2.6
*Platform:* Windows

### Steps to Reproduce
Run any `exists?`

### Expected Result
Use a standard `like` method instead of custom `find_bys`

### Actual Result
Currently there are several different `find_bys` being used, some use `unique_id`, some use the whole `@data`, others are completely ignored.

**Comment by marikrg** [comment]
@abiliogp take a look on this issue, it's related with the changes you are working

**Comment by VenkateshRavula** [comment]
Refer this PR to start with.
https://github.com/HewlettPackard/oneview-puppet/pull/138

**Comment by VenkateshRavula** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
