### ISSUE TITLE
Scope Uris not being retrieved automatically

### ISSUE THREAD

**Issue by fgbulsoni** [HewlettPackard/oneview-puppet#67]
### Scenario/Intent
Insert a name for Scope Uris and it automatically get the correct resource for it

### Environment Details
*Puppet module for HPE OneView Version:* 2.0.0
*OneView SDK Version:* 3.1.0
*OneView Appliance Version:* 3.0
*OneView Client API Version:* 300
*Puppet Version:* 4.8
*Ruby Version:* 2.2.6
*Platform:* Windows

### Steps to Reproduce
Insert a name instead of a '/rest/etc' uri on a scope uri field

### Expected Result
Should "automagically" get the resource uri

### Actual Result
Currently does not work / this is not yet implemented on the ruby sdk

**Comment by VenkateshRavula** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
